### ISSUE TITLE
create gh-pages branch for free web hosting!

### ISSUE THREAD

**Issue by nii236** [learntocodemeetup/learncoding-website#3]

**Comment by meagantan** [comment]
how do you do this?

**Comment by nii236** [comment]
Have a look [here](https://pages.github.com/).

**Comment by cyber2024** [comment]
Johnny already made the site some time ago... http://learntocodemeetup.github.io/

**Comment by cyber2024** [comment]
You can setup a custom url also, but we already have this set up

**Comment by danielalbertjeffery** [comment]
I'm not sure who Cyber 2024 is?

**Comment by cyber2024** [comment]
Russ2024

**Comment by nii236** [comment]
Yeah I should really do something about that website. Maybe take it down?

**Comment by meagantan** [comment]
I'd be happy if it was taken down, up to you.

**Comment by nii236** [comment]
Its gone!

**Comment by cyber2024** [comment]
okily dokily!
